### ISSUE TITLE
Block implicitly retains self

### ISSUE THREAD

**Issue by jeffallen** [TheLevelUp/ZXingObjC#427]
XCode gives this little warning:

```
.../Pods/ZXingObjC/ZXingObjC/client/ZXCGImageLuminanceSource.m:242:7: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
```

Thanks for a nice stable library!

**Comment by benjohnde** [comment]
As @neacao mentioned, CocoaPods are not up2date. I will look later on if I can update those as well. I believe I need additional rights to do so.

**Comment by jeffallen** [comment]
So, I updated the tag to 3.4.0 in the podspec and ran pod lint and here's what came out:
```
 -> ZXingObjC (3.4.0)
    - NOTE  | [ZXingObjC/All, ZXingObjC/Core, ZXingObjC/Aztec, and more...] xcodebuild:  note: Using new build system
    - NOTE  | [ZXingObjC/All, ZXingObjC/Core, ZXingObjC/Aztec, and more...] xcodebuild:  note: Planning build
    - NOTE  | [ZXingObjC/All, ZXingObjC/Core, ZXingObjC/Aztec, and more...] xcodebuild:  note: Constructing build description
    - NOTE  | [ZXingObjC/All, ZXingObjC/Core, ZXingObjC/Aztec, and more...] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
    - WARN  | [ZXingObjC/All,ZXingObjC/QRCode] xcodebuild:  ZXingObjC/ZXingObjC/qrcode/detector/ZXQRCodeFinderPatternFinder.m:221:11: warning: parameter 'maxCount' not found in the function declaration [-Wdocumentation]
    - WARN  | [ZXingObjC/All,ZXingObjC/QRCode] xcodebuild:  ZXingObjC/ZXingObjC/qrcode/detector/ZXQRCodeFinderPatternFinder.m:223:11: warning: parameter 'originalStateCountTotal' not found in the function declaration [-Wdocumentation]
    - WARN  | [ZXingObjC/All,ZXingObjC/DataMatrix] xcodebuild:  ZXingObjC/ZXingObjC/datamatrix/ZXDataMatrixWriter.m:143:11: warning: parameter 'reqHeight' not found in the function declaration [-Wdocumentation]
    - WARN  | [ZXingObjC/All,ZXingObjC/DataMatrix] xcodebuild:  ZXingObjC/ZXingObjC/datamatrix/ZXDataMatrixWriter.m:144:11: warning: parameter 'reqWidth' not found in the function declaration [-Wdocumentation]
    - WARN  | [ZXingObjC/All,ZXingObjC/DataMatrix] xcodebuild:  ZXingObjC/ZXingObjC/datamatrix/ZXDataMatrixWriter.m:145:11: warning: parameter 'input' not found in the function declaration [-Wdocumentation]
    - WARN  | [ZXingObjC/All,ZXingObjC/PDF417] xcodebuild:  ZXingObjC/ZXingObjC/pdf417/decoder/ZXPDF417DecodedBitStreamParser.m:228:40: warning: implicit conversion loses integer precision: 'long long' to 'long' [-Wshorten-64-to-32]
    - WARN  | [ZXingObjC/All,ZXingObjC/PDF417] xcodebuild:  ZXingObjC/ZXingObjC/pdf417/decoder/ZXPDF417DecodedBitStreamParser.m:242:39: warning: implicit conversion loses integer precision: 'long long' to 'long' [-Wshorten-64-to-32]
    - ERROR | [ZXingObjC/All, ZXingObjC/Core, ZXingObjC/Aztec, and more...] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS] [ZXingObjC/DataMatrix] xcodebuild:  warning: 
    - NOTE  | [iOS] [ZXingObjC/DataMatrix] xcodebuild:  11: warning: parameter 'input' not found in the function declaration [-Wdocumentation]
```

So, that would be a big 👎

**Comment by benjohnde** [comment]
Going to look into that later on. Haven’t uploaded to CocoaPods yet 🤔

**Comment by benjohnde** [comment]
@jeffallen hang tight until tomorrow, I will fix those outstanding warnings (I dunno right now why you receive an error) and will release a new version to [CocoaPods](https://cocoapods.org/pods/ZXingObjC). The last release currently is `3.2.2`.

**Comment by benjohnde** [comment]
verbose run released the following error messages:

```
[...]
    PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/bjohn/Library/Developer/Xcode/DerivedData/App-giuanxbwzzyeahcwslqovuspgrnp/Build/Intermediates.noindex/App.build/Release/App.build/Script-54620F6A057A58E4562C1180.sh (in target: App)
        cd /var/folders/_s/0ldz4jbx7rz8bxfnswbks3pm0000gn/T/CocoaPods-Lint-20180925-48368-1tznay5-ZXingObjC
        /bin/sh -c /Users/bjohn/Library/Developer/Xcode/DerivedData/App-giuanxbwzzyeahcwslqovuspgrnp/Build/Intermediates.noindex/App.build/Release/App.build/Script-54620F6A057A58E4562C1180.sh
    mkdir -p /Users/bjohn/Library/Developer/Xcode/DerivedData/App-giuanxbwzzyeahcwslqovuspgrnp/Build/Products/Release/App.app/Contents/Frameworks
    rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/bjohn/Library/Developer/Xcode/DerivedData/App-giuanxbwzzyeahcwslqovuspgrnp/Build/Products/Release/ZXingObjC/ZXingObjC.framework" "/Users/bjohn/Library/Developer/Xcode/DerivedData/App-giuanxbwzzyeahcwslqovuspgrnp/Build/Products/Release/App.app/Contents/Frameworks"
    building file list ... done
    ZXingObjC.framework/
    ZXingObjC.framework/Resources -> Versions/Current/Resources
    ZXingObjC.framework/ZXingObjC -> Versions/Current/ZXingObjC
    ZXingObjC.framework/Versions/
    ZXingObjC.framework/Versions/Current -> A
    ZXingObjC.framework/Versions/A/
    ZXingObjC.framework/Versions/A/ZXingObjC
    ZXingObjC.framework/Versions/A/Resources/
    ZXingObjC.framework/Versions/A/Resources/Info.plist

    sent 638797 bytes  received 106 bytes  1277806.00 bytes/sec
    total size is 638318  speedup is 1.00
    /var/folders/_s/0ldz4jbx7rz8bxfnswbks3pm0000gn/T/CocoaPods-Lint-20180925-48368-1tznay5-ZXingObjC/Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh: line 104: EXPANDED_CODE_SIGN_IDENTITY: unbound variable
    Command PhaseScriptExecution failed with a nonzero exit code

    ** BUILD FAILED **


    The following build commands failed:
    	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/bjohn/Library/Developer/Xcode/DerivedData/App-giuanxbwzzyeahcwslqovuspgrnp/Build/Intermediates.noindex/App.build/Release/App.build/Script-54620F6A057A58E4562C1180.sh
    (1 failure)
   Testing with `xcodebuild`.
 -> ZXingObjC (3.4.0)
    - NOTE  | [ZXingObjC/All, ZXingObjC/Core, ZXingObjC/Aztec, and more...] xcodebuild:  note: Using new build system
    - NOTE  | [ZXingObjC/All, ZXingObjC/Core, ZXingObjC/Aztec, and more...] xcodebuild:  note: Planning build
    - NOTE  | [ZXingObjC/All, ZXingObjC/Core, ZXingObjC/Aztec, and more...] xcodebuild:  note: Constructing build description
    - NOTE  | [ZXingObjC/All, ZXingObjC/Core, ZXingObjC/Aztec, and more...] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
    - WARN  | [ZXingObjC/All,ZXingObjC/QRCode] xcodebuild:  /Users/bjohn/git/ZXingObjC/ZXingObjC/qrcode/detector/ZXQRCodeFinderPatternFinder.m:221:11: warning: parameter 'maxCount' not found in the function declaration [-Wdocumentation]
    - WARN  | [ZXingObjC/All,ZXingObjC/QRCode] xcodebuild:  /Users/bjohn/git/ZXingObjC/ZXingObjC/qrcode/detector/ZXQRCodeFinderPatternFinder.m:223:11: warning: parameter 'originalStateCountTotal' not found in the function declaration [-Wdocumentation]
    - WARN  | [ZXingObjC/All,ZXingObjC/DataMatrix] xcodebuild:  /Users/bjohn/git/ZXingObjC/ZXingObjC/datamatrix/ZXDataMatrixWriter.m:143:11: warning: parameter 'reqHeight' not found in the function declaration [-Wdocumentation]
    - WARN  | [ZXingObjC/All,ZXingObjC/DataMatrix] xcodebuild:  /Users/bjohn/git/ZXingObjC/ZXingObjC/datamatrix/ZXDataMatrixWriter.m:144:11: warning: parameter 'reqWidth' not found in the function declaration [-Wdocumentation]
    - WARN  | [ZXingObjC/All,ZXingObjC/DataMatrix] xcodebuild:  /Users/bjohn/git/ZXingObjC/ZXingObjC/datamatrix/ZXDataMatrixWriter.m:145:11: warning: parameter 'input' not found in the function declaration [-Wdocumentation]
    - WARN  | [ZXingObjC/All,ZXingObjC/PDF417] xcodebuild:  /Users/bjohn/git/ZXingObjC/ZXingObjC/pdf417/decoder/ZXPDF417DecodedBitStreamParser.m:228:40: warning: implicit conversion loses integer precision: 'long long' to 'long' [-Wshorten-64-to-32]
    - WARN  | [ZXingObjC/All,ZXingObjC/PDF417] xcodebuild:  /Users/bjohn/git/ZXingObjC/ZXingObjC/pdf417/decoder/ZXPDF417DecodedBitStreamParser.m:242:39: warning: implicit conversion loses integer precision: 'long long' to 'long' [-Wshorten-64-to-32]
    - ERROR | [ZXingObjC/All, ZXingObjC/Core, ZXingObjC/Aztec, and more...] xcodebuild: Returned an unsuccessful exit code.

[!] ZXingObjC did not pass validation, due to 1 error and 7 warnings.
You can use the `--no-clean` option to inspect any issue.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/lib/lint.rb:85:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/lib/lint.rb:54:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/lib/lint.rb:54:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
[...]
```


https://github.com/CocoaPods/CocoaPods/issues/7708

**Comment by benjohnde** [comment]
@jeffallen https://cocoapods.org/pods/ZXingObjC

As of now, you should be able to use:

```
platform :ios, '8.0'
pod 'ZXingObjC', '~> 3.4.0'
```

🎉
